import {
  faPlus,
  faTimes,
  faWandMagicSparkles
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useCallback, useEffect, useRef, useState } from 'react';
import { safeGetHostname } from '../../../utils/helpers';
import { buildSyncContext, invalidateSyncContext } from '../../../services/syncContextService';
import WorkspaceSidebar from './WorkspaceSidebar';
import WorkspaceEditor from './WorkspaceEditor';
import AISuggestionPanel from './AISuggestionPanel';
import AIPromptBar from './AIPromptBar';
import { useBrowserData } from './useBrowserData';
import { useAISuggestions } from './useAISuggestions';
import { useMemory } from './useMemory';
import './AIWorkspaceManager.css';

export default function AIWorkspaceManager({
  workspaces = [],
  onSave,
  onDelete,
  isOpen: externalIsOpen,
  onOpen: externalOnOpen,
  onClose: externalOnClose,
  initialWorkspace,
  showFab = true,
  ...rest
}) {
  // Support both controlled and uncontrolled modes
  const [internalIsOpen, setInternalIsOpen] = useState(false);
  const isControlled = externalIsOpen !== undefined;
  const isOpen = isControlled ? externalIsOpen : internalIsOpen;

  const handleOpen = useCallback(() => {
    if (isControlled) {
      externalOnOpen?.();
    } else {
      setInternalIsOpen(true);
    }
  }, [isControlled, externalOnOpen]);

  const handleClose = useCallback(() => {
    if (isControlled) {
      externalOnClose?.();
    } else {
      setInternalIsOpen(false);
    }
  }, [isControlled, externalOnClose]);

  // Core state
  const [selectedWorkspaceId, setSelectedWorkspaceId] = useState(null);
  const [mode, setMode] = useState('suggestions'); // 'suggestions' | 'edit' | 'create'

  // Form state
  const [formData, setFormData] = useState({
    id: null,
    name: '',
    icon: 'folder',
    description: '',
    urls: [],
    apps: [],
    createdAt: null
  });

  // AI-suggested URLs for current workspace (edit mode)
  const [relatedUrls, setRelatedUrls] = useState([]);
  const [relatedUrlsLoading, setRelatedUrlsLoading] = useState(false);

  // Memory context (enriched hint string fetched from feedback store)
  const [memoryContext, setMemoryContext] = useState('');
  // Cleaned sync-data context (workspaces + activity from sidecar)
  const [syncContext, setSyncContext] = useState('');

  // Browser data hook
  const { tabs, history, bookmarks, isLoading: browserDataLoading, refresh: refreshBrowserData } = useBrowserData(isOpen);

  // AI suggestions hook
  const {
    aiPrompt,
    setAiPrompt,
    suggestions,
    isLoading: aiLoading,
    error: aiError,
    generateSuggestions,
    suggestRelatedUrls
  } = useAISuggestions(tabs, workspaces);

  // Memory layer hook
  const memory = useMemory();

  // ── Fetch sync context (workspaces + activity) once on open ───────────────
  useEffect(() => {
    if (!isOpen) return;
    buildSyncContext().then(ctx => setSyncContext(ctx));
  }, [isOpen]);

  // ── Auto-generate with memory context once tabs are ready ──────────────────
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (!isOpen) {
      // Reset auto-generate flag when dialog closes so re-opening refreshes
      hasAutoGeneratedRef.current = false;
      return;
    }
    if (tabs.length < 3 || hasAutoGeneratedRef.current) return;
    if (initialWorkspace) return; // opened in edit mode — skip auto-generate

    hasAutoGeneratedRef.current = true;

    // Load learned patterns first, then generate suggestions with that context
    memory.loadMemoryContext(tabs).then(ctx => {
      setMemoryContext(ctx);
      generateSuggestions('', ctx, null, syncContext);
    });
  }, [tabs, isOpen, initialWorkspace, syncContext]);

  // ── Record ignored suggestions when dialog closes ─────────────────────────
  const suggestionsRef = useRef(suggestions);
  useEffect(() => { suggestionsRef.current = suggestions; }, [suggestions]);

  useEffect(() => {
    if (!isOpen && suggestionsRef.current.length > 0) {
      memory.recordIgnoredSuggestions(suggestionsRef.current);
    }
  }, [isOpen]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && isOpen) {
        handleClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, handleClose]);

  // Initialize from props
  useEffect(() => {
    if (isOpen) {
      if (initialWorkspace) {
        setSelectedWorkspaceId(initialWorkspace.id);
        setMode('edit');
        setFormData({
          id: initialWorkspace.id,
          name: initialWorkspace.name || '',
          icon: initialWorkspace.icon || 'folder',
          description: initialWorkspace.description || '',
          urls: initialWorkspace.urls || [],
          apps: initialWorkspace.apps || [],
          createdAt: initialWorkspace.createdAt || Date.now()
        });
      } else {
        setSelectedWorkspaceId(null);
        setMode('suggestions');
        resetForm();
      }
    }
  }, [isOpen, initialWorkspace]);

  // Load workspace data when selection changes
  useEffect(() => {
    // Clear suggestions immediately when workspace changes
    setRelatedUrls([]);
    setRelatedUrlsLoading(false);

    if (selectedWorkspaceId && mode === 'edit') {
      const workspace = workspaces.find(ws => ws.id === selectedWorkspaceId);
      if (workspace) {
        setFormData({
          id: workspace.id,
          name: workspace.name || '',
          icon: workspace.icon || 'folder',
          description: workspace.description || '',
          urls: workspace.urls || [],
          apps: workspace.apps || [],
          createdAt: workspace.createdAt || Date.now()
        });

        // Fetch AI-suggested URLs for this workspace (from user's actual history)
        if (workspace.urls?.length > 0) {
          setRelatedUrlsLoading(true);
          suggestRelatedUrls(workspace, history, bookmarks)
            .then(urls => {
              // Only set if still the same workspace (avoid race condition)
              setRelatedUrls(urls);
            })
            .catch(() => setRelatedUrls([]))
            .finally(() => setRelatedUrlsLoading(false));
        }
      }
    }
  }, [selectedWorkspaceId, mode, workspaces, suggestRelatedUrls, history, bookmarks]);

  const resetForm = useCallback(() => {
    setFormData({
      id: null,
      name: '',
      icon: 'folder',
      description: '',
      urls: [],
      apps: [],
      createdAt: null
    });
  }, []);

  const handleSelectWorkspace = useCallback((workspace) => {
    setSelectedWorkspaceId(workspace.id);
    setMode('edit');
  }, []);

  const handleCreateNew = useCallback(() => {
    setSelectedWorkspaceId(null);
    setMode('create');
    resetForm();
  }, [resetForm]);

  const handleAcceptSuggestion = useCallback((group) => {
    // Record positive feedback before switching mode (fire-and-forget)
    memory.recordAcceptedSuggestion(group, tabs);

    setMode('create');
    setSelectedWorkspaceId(null);

    // Map group items (indices) back to actual URLs
    const groupUrls = (group.items || [])
      .map(idx => tabs[idx - 1])
      .filter(Boolean)
      .map(tab => ({
        url: tab.url,
        title: tab.title,
        favicon: tab.favicon,
        addedAt: Date.now()
      }));

    // Also include suggested URLs from AI
    const suggestedUrls = (group.suggestedUrls || [])
      .filter(su => su.url)
      .map(su => ({
        url: su.url,
        title: su.title || '',
        favicon: null,
        addedAt: Date.now()
      }));

    // Deduplicate by URL
    const allUrls = [...groupUrls];
    const existingUrlSet = new Set(allUrls.map(u => u.url));
    suggestedUrls.forEach(su => {
      if (!existingUrlSet.has(su.url)) {
        allUrls.push(su);
        existingUrlSet.add(su.url);
      }
    });

    setFormData({
      id: null,
      name: group.name || '',
      icon: 'folder',
      description: group.description || '',
      urls: allUrls,
      apps: [],
      createdAt: null
    });
  }, [tabs, memory]);

  const handleSave = useCallback(async () => {
    if (!formData.name.trim()) return;

    const workspaceData = {
      ...formData,
      id: formData.id || `ws_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      updatedAt: Date.now(),
      createdAt: formData.createdAt || Date.now()
    };

    try {
      await onSave?.(workspaceData);
      // Record URL → workspace associations for future memory enrichment
      memory.recordWorkspaceSaved(workspaceData);
      // Invalidate sync context so the next open reflects the new workspace
      invalidateSyncContext();
      handleClose();
    } catch (err) {
      console.error('Failed to save workspace:', err);
    }
  }, [formData, onSave, handleClose, memory]);

  const handleDelete = useCallback(async () => {
    if (!formData.id) return;

    const confirmed = window.confirm(`Delete workspace "${formData.name}"? This cannot be undone.`);
    if (!confirmed) return;

    try {
      await onDelete?.(formData.id);
      handleClose();
    } catch (err) {
      console.error('Failed to delete workspace:', err);
    }
  }, [formData.id, formData.name, onDelete, handleClose]);

  // Unified handler for adding URLs and apps from the selector
  const handleAddItems = useCallback(({ urls = [], apps = [] }) => {
    // Deduplicate URLs
    const existingUrls = new Set(formData.urls.map(u => u.url));
    const uniqueNewUrls = urls.filter(u => !existingUrls.has(u.url));

    // Deduplicate Apps
    const existingPaths = new Set((formData.apps || []).map(a => a.path));
    const uniqueNewApps = apps.filter(a => !existingPaths.has(a.path));

    setFormData(prev => ({
      ...prev,
      urls: [...prev.urls, ...uniqueNewUrls],
      apps: [...(prev.apps || []), ...uniqueNewApps]
    }));

    // Record URL → workspace associations
    if (formData.name && uniqueNewUrls.length > 0) {
      memory.recordUrlsAddedToWorkspace(uniqueNewUrls, formData.name);
    }
  }, [formData.urls, formData.apps, formData.name, memory]);

  const handleRemoveUrl = useCallback((urlToRemove) => {
    setFormData(prev => ({
      ...prev,
      urls: prev.urls.filter(u => u.url !== urlToRemove)
    }));
  }, []);

  const handleRemoveApp = useCallback((appPath) => {
    setFormData(prev => ({
      ...prev,
      apps: (prev.apps || []).filter(a => a.path !== appPath)
    }));
  }, []);

  const handleAddRelatedUrl = useCallback((urlItem) => {
    // Check if already exists
    if (formData.urls.some(u => u.url === urlItem.url)) return;

    const newUrl = {
      url: urlItem.url,
      title: urlItem.title || '',
      favicon: urlItem.favicon || urlItem.favIconUrl,
      addedAt: Date.now()
    };

    setFormData(prev => ({
      ...prev,
      urls: [...prev.urls, newUrl]
    }));

    // Remove from suggestions list
    setRelatedUrls(prev => prev.filter(u => u.url !== urlItem.url));

    // Record association
    if (formData.name) {
      memory.recordUrlsAddedToWorkspace([newUrl], formData.name);
    }
  }, [formData.urls, formData.name, memory]);

  const handleUpdateForm = useCallback((field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  }, []);

  // When a workspace-context prompt returns suggestions, pipe suggestedUrls into relatedUrls
  // so they are visible in WorkspaceEditor (which doesn't show the AISuggestionPanel).
  const lastPromptHadWorkspaceContext = useRef(false);
  useEffect(() => {
    if (!lastPromptHadWorkspaceContext.current) return;
    if (suggestions.length === 0) return;

    const newSuggested = suggestions
      .flatMap(g => g.suggestedUrls || [])
      .filter(su => su?.url)
      .map(su => ({
        url: su.url,
        title: su.title || safeGetHostname(su.url),
        reason: su.reason || 'AI suggested',
        _aiSuggested: true
      }));

    if (newSuggested.length > 0) {
      setRelatedUrls(prev => {
        const existing = new Set(prev.map(u => u.url));
        return [...prev, ...newSuggested.filter(u => !existing.has(u.url))];
      });
    }
  }, [suggestions]);

  // Manual send: refresh memory context then generate
  const handlePromptSubmit = useCallback(async (promptText) => {
    const ctx = await memory.loadMemoryContext(tabs);
    setMemoryContext(ctx);
    // Pass current workspace as context when editing/creating so the AI prompt
    // focuses on finding relevant URLs for that workspace rather than grouping tabs.
    const wsContext = (mode === 'edit' || mode === 'create') && formData.name ? formData : null;
    lastPromptHadWorkspaceContext.current = !!wsContext;
    generateSuggestions(promptText, ctx, wsContext, syncContext);
  }, [memory, tabs, generateSuggestions, mode, formData, syncContext]);

  if (!isOpen) return null;

  return (
    <div className="ai-workspace-manager-overlay" onClick={handleClose}>
      <div className="ai-workspace-manager" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="awm-header">
          <h2>
            <FontAwesomeIcon icon={faWandMagicSparkles} className="awm-header-icon" />
            AI Workspace Manager
          </h2>
          <button className="awm-close-btn" onClick={handleClose}>
            <FontAwesomeIcon icon={faTimes} />
          </button>
        </div>

        <div className="awm-content">
          {/* Left Panel - Sidebar */}
          <WorkspaceSidebar
            workspaces={workspaces}
            selectedId={selectedWorkspaceId}
            onSelect={handleSelectWorkspace}
            onCreateNew={handleCreateNew}
          />

          {/* Right Panel */}
          <div className="awm-main-panel">
            {/* AI Prompt Bar */}
            <AIPromptBar
              value={aiPrompt}
              onChange={setAiPrompt}
              onSubmit={handlePromptSubmit}
              isLoading={aiLoading}
            />

            {/* Main Content Area */}
            <div className="awm-main-content">
              {mode === 'suggestions' ? (
                <AISuggestionPanel
                  suggestions={suggestions}
                  isLoading={aiLoading || browserDataLoading}
                  error={aiError}
                  onAccept={handleAcceptSuggestion}
                  onCreateNew={handleCreateNew}
                />
              ) : (
                <WorkspaceEditor
                  formData={formData}
                  onUpdate={handleUpdateForm}
                  onRemoveUrl={handleRemoveUrl}
                  onRemoveApp={handleRemoveApp}
                  onSave={handleSave}
                  onDelete={handleDelete}
                  isNewWorkspace={mode === 'create'}
                  tabs={tabs}
                  history={history}
                  bookmarks={bookmarks}
                  relatedUrls={relatedUrls}
                  relatedUrlsLoading={relatedUrlsLoading}
                  onAddItem={handleAddItems}
                />
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
