[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[env]
MACOSX_DEPLOYMENT_TARGET = { value = "11.0", force = true }
CXXFLAGS = { value = "-D_LIBCPP_DISABLE_AVAILABILITY", force = true }
